CUDA_VISIBLE_DEVICES=0 python ./src/model/bart_kv/train.py \
    --data_path ./data/slotsum/clipped \
    --output_path ./models/bart_kv/bart-large \
    --base_model ./models/pretrained/bart-large \
    --data_format json \
    --seq_max_length 512 \
    --cuda \
    --learning_rate 1e-5 \
    --epoch 4 \
    --train_batch_size 4 \
    --eval_batch_size 8 \
    --print_interval 100 \
    --seed 42